global:
  scrape_interval:     10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'spring-boot-app'
    metrics_path: '/outcurrapi/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9092']

