global:
  scrape_interval:     10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'spring-boot-app'
    metrics_path: '/outcurrapi/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9092']

remote_write:
  - url: "http://prometheus:9091/write"