apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true
    uid: Prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    uid: Loki