{
 "title": "Gestión Curr Personalizado",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Request",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OK (200) Requests",
   "type": "stat",
   "gridPos": { "h": 12, "w": 11, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    http_server_requests_seconds_count{\r\n      status=\"200\", \r\n      instance=\"host.docker.internal:9092\"    \r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "N. Of Waring Logs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"demo_logs\", level=\"WARN\"}[1h])"
    }
   ]
  },
  {
   "title": "N. of Info Logs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"demo_logs\", level=\"INFO\"}[1h])"
    }
   ]
  },
  {
   "title": "Number of Faculties Created",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_of_faculties_created_total{application=\"outcome-curr-mgmnt\",method=\"createFaculty\",instance=\"host.docker.internal:9092\",}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}