{
 "title": "Gestión Curr Personalizado",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Request",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "N. Of Waring Logs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"demo_logs\", level=\"WARN\"}[1h])"
    }
   ]
  },
  {
   "title": "N. of Info Logs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"demo_logs\", level=\"INFO\"}[1h])"
    }
   ]
  }
 ]
}